# Generated by Django 2.1.3 on 2018-12-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20181127_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='license',
            field=models.CharField(choices=[('FRE', 'Free of charges'), ('AM', 'Amayuelas')], max_length=3),
        ),
        migrations.AlterField(
            model_name='photo',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Private')], default='PUB', max_length=3),
        ),
    ]
